version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
install:
- cmd: >-
    curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe

    dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log
build_script:
- cmd: >-
    dotnet restore src\GdaxApi.Feed.sln

    dotnet pack src\Gdax.Feed\Gdax.Feed.csproj -o artifacts\packages -c Release
test: off
artifacts:
- path: src\Gdax.Feed\artifacts\packages\*.nupkg
deploy: off